// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package ru.pobopo.weather.grpc;

public interface CreditsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ru.pobopo.weather.grpc.Credits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string login = 1;</code>
   */
  java.lang.String getLogin();
  /**
   * <code>string login = 1;</code>
   */
  com.google.protobuf.ByteString
      getLoginBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
